import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./nav/page";
import Header from "./header/page";
import Footer from "./footer/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-slate-100">
      <body className={inter.className}>
        <Nav />
       
        <main>{children}</main>
        <Footer /> 
      </body>
    </html>
  );
}
